"""
globals.py - Shared constants and global variables.

WARNING: DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING.
Configuration should be done in env.py.
"""

import sys
from pathlib import Path

# Internal paths
SCRIPT_DIR = Path(__file__).parent.resolve()
CHECK_FILE = SCRIPT_DIR / "checkme.txt"
LOG_DIR = SCRIPT_DIR / "logs"
DETACHED_FILE = SCRIPT_DIR / ".detached.json"

# Terminal colors via ansi escape codes
RED = "\033[91m"
YELLOW = "\033[93m"
GREEN = "\033[92m"
BLUE = "\033[94m"
MAGENTA = "\033[95m"
RESET = "\033[0m"

# Safe import of env.py
try:
    import env
except ImportError:
    print(f"{RED}ERROR: 'env.py' is missing.{RESET}")
    print("Please copy 'env.py.example' to 'env.py' and configure it.")
    sys.exit(1)


def _get_env_var(name, required=True):
    if hasattr(env, name):
        return getattr(env, name)
    if required:
        print(f"{RED}Missing required variable '{name}' in env.py.{RESET}")
        print("Please check 'env.py.example' for the correct structure.")
        sys.exit(1)
    return None


# Required configuration
VOD_ROOT_STR = _get_env_var("VOD_ROOT")
LOG_ROOT_STR = _get_env_var("LOG_ROOT")
RELOAD_INTERVAL = _get_env_var("RELOAD_INTERVAL")
PROBE_INTERVAL = _get_env_var("PROBE_INTERVAL")
PLATFORM_COOLDOWN = _get_env_var("PLATFORM_COOLDOWN")

# Optional configuration (but variable must exist, even if empty string, based on example)
DISCORD_WEBHOOK_URL = _get_env_var("DISCORD_WEBHOOK_URL")
YOUTUBE_API_KEY = _get_env_var("YOUTUBE_API_KEY")
TWITCH_CLIENT_ID = _get_env_var("TWITCH_CLIENT_ID")
TWITCH_CLIENT_SECRET = _get_env_var("TWITCH_CLIENT_SECRET")
TWITCH_OAUTH_TOKEN = _get_env_var("TWITCH_OAUTH_TOKEN")

# Path objects
VOD_ROOT = Path(VOD_ROOT_STR)
LOG_ROOT = Path(LOG_ROOT_STR)

# Recording constants
MAX_YT_HEIGHT = 1080
STREAMLINK_SEGMENT_ATTEMPTS = 3
STREAMLINK_SEGMENT_TIMEOUT = 10.0
STREAMLINK_TIMEOUT = 60.0
